### PR TITLE
return Result instead of unwrapping

### PR DESCRIPTION
**Pull request by meehow**

### CODE REVIEW

**Comment by gsquire** [comment]
These changes look good. Since this is technically a breaking change to the API, I want to test it some myself. If things go well, I'll have you squash and then I will merge these.

I'll add your name to the README for your recent contributions too. Much appreciated :+1:

**Comment by meehow** [comment]
I wouldn't say that this change could break something. If somebody managed to use this library, which can crash a program, and has version "0.1" in dependencies, then this change will only generate a warning `unused result which must be used`.

**Comment by gsquire** [comment]
I guess I meant in the sense that the functions will return results now. But overall it is a much needed change, so thank you.

**Comment by gsquire** [comment]
Can you please squash your commits so I can merge this @meehow?

**Pull request merged**
