### PR TITLE
improve: derive more

### PR DESCRIPTION
**Pull request by GopherJ**
Signed-off-by: Cheng JIANG <alex_cj96@foxmail.com>

close: #79

### CODE REVIEW

**Comment by GopherJ** [comment]
derive `Default` will make it possible to write:

```rust
let mut p = Personalization::default();
p.add_to(...)
```

**Comment by GopherJ** [comment]
@gsquire hi could you have a look, thanks

**Comment by gsquire** [comment]
Hey, @GopherJ. I am currently moving out of state so it'll be a little while before I can review. I'm sorry for the delay!

**Review by gsquire — CHANGES_REQUESTED** [review]
Sorry this sat for a bit. I should be able to respond much quicker now after the new year. Just one minor comment and then we can land this.

**Comment by gsquire** [comment]
Closing, see https://github.com/gsquire/sendgrid-rs/issues/79#issuecomment-2330249538.

**Pull request closed without merging**
