### PR TITLE
SGClient: Add Clone + Debug traits

### PR DESCRIPTION
**Pull request by z0mbie42**

### CODE REVIEW

**Comment by gsquire** [comment]
Thanks for adding this! I'll publish 0.8.1 with this patch shortly.

**Comment by z0mbie42** [comment]
Ack :)

Can you also add them to the v3 `Sender` struct please ?

I'm on mobile and it doesn't work

**Comment by gsquire** [comment]
Published 0.8.1 with both types now implementing Clone and Debug.

**Comment by z0mbie42** [comment]
Thank you!

**Pull request merged**
