### PR TITLE
Compile with async feature flag

### PR DESCRIPTION
**Pull request by peitalin**
Hello,

I've added the option to build `sendgrid-rs` with the async client from reqwest.
This allows you to use `sendgrid-rs` with async frameworks like tokio, actix, etc.

Regards,
Peita

### CODE REVIEW

**Comment by gsquire** [comment]
Hey, @peitalin. Thanks for submitting this!

Sorry it took a while to get around to reviewing this. At a high level, do you think we could add this code to the existing module as a conditional compilation using the same feature flag you added? It seems like some of the code is duplicated.

Also, I think SendGrid suggests users develop against V3 of the API. It'd be great to get this merged in and I am happy to work through it.

**Comment by peitalin** [comment]
Do you mean also adding the `v3.rs` module to be compiled using the `async` flag?

**Comment by gsquire** [comment]
Adding it to the v3 module would be great.

What I mean with regards to my other comments is that i think this could be added as a sub module within the existing module. And then we can add a conditional compilation to enable it. The docs I am referring to can be [seen here](https://doc.rust-lang.org/1.19.0/book/first-edition/conditional-compilation.html). This will cut down on some of the code duplication.

**Comment by gsquire** [comment]
@peitalin Thanks for you work on this but I ended up merging #48.

Please create an issue if anything seems wrong.

**Pull request closed without merging**
